export default {
	LOGIN: '/api/user/login',
	REGISTER: '/api/user/register',
	LOGOUT: '/api/user/logout',
	APPLICATION: '/api/live/application',
	LIVELIST: '/api/live',
	SMSCODE: '/api/user/smscode',
	GROUPLIST: '/api/admin/getLiveGroupList',
	LIVELISTBYGROUPID: '/api/admin/getInfoByGroupId',
	LIVEINFOBYROOMID: '/api/live/getLiveInfoByRoomId',
	GETGIFTLISTBYUSERID: '/api/gift/getGiftListByUserId',
	USERBYID: '/api/admin/userById',
	SENDGIFT: '/api/gift/sendGIft',
	GETRICHPEOPLE: '/api/gift/getRichPeopleByUserIdAndRoomId',
	GETWANTEDSTATUSBYUSERID:'/api/wanted/getStatusByUserId',
	SendWantedByUserId:'/api/wanted/sendWantedByUserId',
	SendWantedByUserIdAgain:'/api/wanted/sendWantedByUserIdAgain',
	GetDefaultGiftList:'/api/gift/getDefaultGiftList',
	ApplicationLive:'/api/live/application',
	GetLivListByAttendance:'/api/live/getLivListByAttendance',
}